apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messenger-dev

resources:
  - ../../base

labels:
  - pairs:
      environment: dev
      managed-by: kustomize

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1